version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=products
    volumes:
      - mysqldata:/data/mysql
  api:
    container_name: api--product-stock
    image: api--product-stock
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/products
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: products
    links:
      - db
    volumes:
      - ./:/src

volumes:
  mysqldata: